### ISSUE TITLE
 secondaryCountry = secondaryObject.find('Country').text makes problems

### ISSUE THREAD

**Issue by derbuur** [jvanlint/pytacview#2]
In line 173  secondaryCountry = secondaryObject.find('Country').text 
get the error message:   secondaryCountry = secondaryObject.find('Country').text

Solved the problem by deleting line 173 and adding
if secondaryObject.find('Country') is not None:
    secondaryCountry = secondaryObject.find('Country').text
else:
    secondaryCountry = ""

greetings

**Comment by jvanlint** [comment]
Code changed as recommended. Thanks derbuur for reporting and fixing
